-- MySQL Script generated by MySQL Workbench
-- Wed Dec 21 21:34:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbCalendar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbCalendar` ;

-- -----------------------------------------------------
-- Schema dbCalendar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbCalendar` DEFAULT CHARACTER SET utf8 ;
USE `dbCalendar` ;

-- -----------------------------------------------------
-- Table `dbCalendar`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbCalendar`.`Student` ;

CREATE TABLE IF NOT EXISTS `dbCalendar`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCalendar`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbCalendar`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `dbCalendar`.`Teacher` (
  `idTeacher` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTeacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCalendar`.`Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbCalendar`.`Subjects` ;

CREATE TABLE IF NOT EXISTS `dbCalendar`.`Subjects` (
  `idSubject` INT NOT NULL AUTO_INCREMENT,
  `nameSubject` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSubject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCalendar`.`Speciality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbCalendar`.`Speciality` ;

CREATE TABLE IF NOT EXISTS `dbCalendar`.`Speciality` (
  `idSpeciality` INT NOT NULL AUTO_INCREMENT,
  `nameSpeciality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSpeciality`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCalendar`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbCalendar`.`Room` ;

CREATE TABLE IF NOT EXISTS `dbCalendar`.`Room` (
  `idRoom` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`idRoom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCalendar`.`Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbCalendar`.`Exam` ;

CREATE TABLE IF NOT EXISTS `dbCalendar`.`Exam` (
  `idExam` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATETIME NOT NULL,
  `duration` INT NOT NULL,
  `Room_idRoom` INT NOT NULL,
  `Subjects_idSubject` INT NOT NULL,
  PRIMARY KEY (`idExam`),
  INDEX `fk_Exam_Room1_idx` (`Room_idRoom` ASC),
  INDEX `fk_Exam_Subjects1_idx` (`Subjects_idSubject` ASC),
  CONSTRAINT `fk_Exam_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `dbCalendar`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exam_Subjects1`
    FOREIGN KEY (`Subjects_idSubject`)
    REFERENCES `dbCalendar`.`Subjects` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCalendar`.`Speciality_has_Subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbCalendar`.`Speciality_has_Subjects` ;

CREATE TABLE IF NOT EXISTS `dbCalendar`.`Speciality_has_Subjects` (
  `Speciality_idSpeciality` INT NOT NULL,
  `Subjects_idSubject` INT NOT NULL,
  PRIMARY KEY (`Speciality_idSpeciality`, `Subjects_idSubject`),
  INDEX `fk_Speciality_has_Subjects_Subjects1_idx` (`Subjects_idSubject` ASC) ,
  INDEX `fk_Speciality_has_Subjects_Speciality_idx` (`Speciality_idSpeciality` ASC) ,
  CONSTRAINT `fk_Speciality_has_Subjects_Speciality`
    FOREIGN KEY (`Speciality_idSpeciality`)
    REFERENCES `dbCalendar`.`Speciality` (`idSpeciality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Speciality_has_Subjects_Subjects1`
    FOREIGN KEY (`Subjects_idSubject`)
    REFERENCES `dbCalendar`.`Subjects` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCalendar`.`supervise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbCalendar`.`supervise` ;

CREATE TABLE IF NOT EXISTS `dbCalendar`.`supervise` (
  `Teacher_idTeacher` INT NOT NULL,
  `Exam_idExam` INT NOT NULL,
  PRIMARY KEY (`Teacher_idTeacher`, `Exam_idExam`),
  INDEX `fk_Teacher_has_Exam_Exam1_idx` (`Exam_idExam` ASC) ,
  INDEX `fk_Teacher_has_Exam_Teacher1_idx` (`Teacher_idTeacher` ASC) ,
  CONSTRAINT `fk_Teacher_has_Exam_Teacher1`
    FOREIGN KEY (`Teacher_idTeacher`)
    REFERENCES `dbCalendar`.`Teacher` (`idTeacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_has_Exam_Exam1`
    FOREIGN KEY (`Exam_idExam`)
    REFERENCES `dbCalendar`.`Exam` (`idExam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbCalendar`.`Student_has_Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbCalendar`.`Student_has_Exam` ;

CREATE TABLE IF NOT EXISTS `dbCalendar`.`Student_has_Exam` (
  `Student_idStudent` INT NOT NULL,
  `Exam_idExam` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Exam_idExam`),
  INDEX `fk_Student_has_Exam_Exam1_idx` (`Exam_idExam` ASC) ,
  INDEX `fk_Student_has_Exam_Student1_idx` (`Student_idStudent` ASC) ,
  CONSTRAINT `fk_Student_has_Exam_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `dbCalendar`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Exam_Exam1`
    FOREIGN KEY (`Exam_idExam`)
    REFERENCES `dbCalendar`.`Exam` (`idExam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
